import type { ProductCategory } from "./types.js";

export const categoryFeatureOptions: Record<ProductCategory, string[]> = {
  gresie: [
    "Matt",
    "Lucios",
    "Satinat",
    "Semi-lucios",
    "Structurat",
    "Sculptat",
    "Texturat",
    "Antiderapant",
    "Natural",
    "Lappato",
    "Polisat",
    "Rectificat",
    "Emailat",
    "Neeemailat",
    "Metalizat",
    "Perlat",
    "Sidefat",
    "Auriu lucios",
    "Auriu mat",
    "Argintiu lucios",
    "Argintiu mat",
    "Cu efect 3D",
  ],
  faianta: [
    "Mată",
    "Lucioasă",
    "Satinată",
    "Lappato",
    "Structurată",
    "Sculptată",
    "Texturată",
    "Netedă",
    "Metalizată",
    "Sidefată",
    "Aurie lucioasă",
    "Aurie mată",
    "Argintie lucioasă",
    "Argintie mată",
    "Cu efect 3D",
    "Oglindă",
    "Emailată",
  ],
  vopsea: [
    "Mată",
    "Ultramată",
    "Catifelată",
    "Satinată",
    "Semi-mată",
    "Semi-lucioasă",
    "Lucioasă",
    "Foarte lucioasă",
    "Metalizată",
    "Sidefată",
    "Perlată",
    "Decorativă",
  ],
  parchet: [
    "Mat",
    "Ultramat",
    "Satinat",
    "Semi-lucios",
    "Lucios",
    "Lăcuit",
    "Uleiat",
    "Uleiat cu ceară",
    "Finisaj invizibil",
    "Lemn brut",
  ],
  adezivi: [
    "Pulbere",
    "Pastă",
    "Lichid",
    "Gel",
    "Spumă",
    "Mastic",
  ],
};

export const featureOptionsForCategory = (category: ProductCategory): string[] =>
  categoryFeatureOptions[category];

export const isValidFeatureForCategory = (category: ProductCategory, feature: string): boolean =>
  featureOptionsForCategory(category).includes(feature);
