export const defaultProduct = {
    productName: "",
    category: "gresie",
    price: 0,
    unit: "m²",
    features: [],
    description: "",
    sizeLabel: "",
    badgeText: "Produs nou",
    productImagePath: "",
};
export const defaultTemplate = {
    id: "manacat-default",
    name: "Template Manacat 1:1",
    width: 1080,
    height: 1080,
    backgroundImagePath: "",
    productLayer: {
        x: 580,
        y: 120,
        width: 380,
        height: 760,
    },
    textBlocks: {
        productName: {
            id: "productName",
            x: 80,
            y: 120,
            maxWidth: 440,
            fontSize: 62,
            lineHeight: 1.05,
            fill: "#ffffff",
            weight: 700,
        },
        subtitle: {
            id: "subtitle",
            x: 80,
            y: 260,
            maxWidth: 420,
            fontSize: 52,
            lineHeight: 1.1,
            fill: "#ffffff",
            weight: 700,
        },
        description: {
            id: "description",
            x: 80,
            y: 390,
            maxWidth: 450,
            fontSize: 38,
            lineHeight: 1.25,
            fill: "#ffffff",
            weight: 500,
        },
        price: {
            id: "price",
            x: 84,
            y: 780,
            maxWidth: 300,
            fontSize: 92,
            lineHeight: 1,
            fill: "#ffffff",
            weight: 800,
        },
        unit: {
            id: "unit",
            x: 360,
            y: 810,
            maxWidth: 170,
            fontSize: 52,
            lineHeight: 1,
            fill: "#ffffff",
            weight: 600,
        },
        size: {
            id: "size",
            x: 84,
            y: 980,
            maxWidth: 260,
            fontSize: 48,
            lineHeight: 1,
            fill: "#ffffff",
            weight: 700,
        },
        feature: {
            id: "feature",
            x: 350,
            y: 980,
            maxWidth: 220,
            fontSize: 52,
            lineHeight: 1,
            fill: "#ffffff",
            weight: 700,
        },
        badge: {
            id: "badge",
            x: 90,
            y: 670,
            maxWidth: 160,
            fontSize: 44,
            lineHeight: 1.05,
            fill: "#ffffff",
            weight: 700,
        },
    },
};
